version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "775:775"
    container_name: nginx
    volumes:
      - ./test.conf:/etc/nginx/sites-enabled/test.conf
      - ./index.html:/usr/alan/nginx/index.html
